[database]
username = "postgres"
connection_url = "localhost/postgres"
pool_size = 20

[email]
server_url = ""
username = ""
pool_size = 20
send_emails = false

[server]
request_timeout = 5
port = 3000
max_unsuccessful_login_attempts = 10
session_length_in_days = 180
